### PR TITLE
Troubleshoot breadcrumb path

### PR DESCRIPTION
**Pull request by raprice**

### CODE REVIEW

**Comment by raprice** [comment]
@andykao1213 Can you please merge when you have a chance? This PR _should_ get the breadcrumbs to render as intended by fixing the breadcrumb path in docfx file.

**Comment by andykao1213** [comment]
@raprice Thanks for the PR :)
Would you mind share what error we are having now and how this is going to fix it?
Also, I cannot map the path you change inside this repo. How can I get the correct path for toc.yml?

**Comment by raprice** [comment]
@andykao1213 Thanks for the questions, it helped me catch an error in my PR, now corrected. This PR is to update the **breadcrumb_path** in the docfx file, because the current breadcrumb_path in the docfx file is incorrect, which means 2 things:
1. The breadcrumbs are not rendering as intended (breadcrumbs on this content should be Learn / Azure)
2. It's flagging broken link errors in our reporting

**Comment by andykao1213** [comment]
@raprice Thanks for answering! One last question: The `breadcrumb_path` is pointed to `toc.json`, but what I can found is [toc.yml](https://github.com/MicrosoftDocs/azure-iot-docs-sdk-typescript/blob/main/bread/toc.yml). Is this a typo? Or it is a different file?

**Comment by raprice** [comment]
Good question, the path does need to point to toc.json, not toc.yml in order to work correctly, thanks for checking - see https://review.learn.microsoft.com/en-us/help/platform/navigation-create-breadcrumb?branch=main#step-2-add-the-breadcrumb-file-path for documentation

**Comment by andykao1213** [comment]
Gotcha. There's no question from my side. Thanks for explaining!

**Pull request merged**
